/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen-v0.34. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"

	filteredapiexportv1alpha1 "github.com/kcp-dev/contrib-filteredapiexport-vw/sdk/apis/filteredapiexport/v1alpha1"
	scheme "github.com/kcp-dev/contrib-filteredapiexport-vw/sdk/clientset/versioned/scheme"
)

// FilteredAPIExportEndpointSlicesGetter has a method to return a FilteredAPIExportEndpointSliceInterface.
// A group's client should implement this interface.
type FilteredAPIExportEndpointSlicesGetter interface {
	FilteredAPIExportEndpointSlices() FilteredAPIExportEndpointSliceInterface
}

// FilteredAPIExportEndpointSliceInterface has methods to work with FilteredAPIExportEndpointSlice resources.
type FilteredAPIExportEndpointSliceInterface interface {
	Create(ctx context.Context, filteredAPIExportEndpointSlice *filteredapiexportv1alpha1.FilteredAPIExportEndpointSlice, opts v1.CreateOptions) (*filteredapiexportv1alpha1.FilteredAPIExportEndpointSlice, error)
	Update(ctx context.Context, filteredAPIExportEndpointSlice *filteredapiexportv1alpha1.FilteredAPIExportEndpointSlice, opts v1.UpdateOptions) (*filteredapiexportv1alpha1.FilteredAPIExportEndpointSlice, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, filteredAPIExportEndpointSlice *filteredapiexportv1alpha1.FilteredAPIExportEndpointSlice, opts v1.UpdateOptions) (*filteredapiexportv1alpha1.FilteredAPIExportEndpointSlice, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*filteredapiexportv1alpha1.FilteredAPIExportEndpointSlice, error)
	List(ctx context.Context, opts v1.ListOptions) (*filteredapiexportv1alpha1.FilteredAPIExportEndpointSliceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *filteredapiexportv1alpha1.FilteredAPIExportEndpointSlice, err error)
	FilteredAPIExportEndpointSliceExpansion
}

// filteredAPIExportEndpointSlices implements FilteredAPIExportEndpointSliceInterface
type filteredAPIExportEndpointSlices struct {
	*gentype.ClientWithList[*filteredapiexportv1alpha1.FilteredAPIExportEndpointSlice, *filteredapiexportv1alpha1.FilteredAPIExportEndpointSliceList]
}

// newFilteredAPIExportEndpointSlices returns a FilteredAPIExportEndpointSlices
func newFilteredAPIExportEndpointSlices(c *FilteredapiexportV1alpha1Client) *filteredAPIExportEndpointSlices {
	return &filteredAPIExportEndpointSlices{
		gentype.NewClientWithList[*filteredapiexportv1alpha1.FilteredAPIExportEndpointSlice, *filteredapiexportv1alpha1.FilteredAPIExportEndpointSliceList](
			"filteredapiexportendpointslices",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *filteredapiexportv1alpha1.FilteredAPIExportEndpointSlice {
				return &filteredapiexportv1alpha1.FilteredAPIExportEndpointSlice{}
			},
			func() *filteredapiexportv1alpha1.FilteredAPIExportEndpointSliceList {
				return &filteredapiexportv1alpha1.FilteredAPIExportEndpointSliceList{}
			},
		),
	}
}
