/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	kcpinformers "github.com/kcp-dev/apimachinery/v2/third_party/informers"
	"github.com/kcp-dev/logicalcluster/v3"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/tools/cache"

	filteredvwv1alpha1 "github.com/kcp-dev/contrib-filteredapiexport-vw/sdk/apis/filteredvw/v1alpha1"
	scopedclientset "github.com/kcp-dev/contrib-filteredapiexport-vw/sdk/client/clientset/versioned"
	clientset "github.com/kcp-dev/contrib-filteredapiexport-vw/sdk/client/clientset/versioned/cluster"
	"github.com/kcp-dev/contrib-filteredapiexport-vw/sdk/client/informers/externalversions/internalinterfaces"
	filteredvwv1alpha1listers "github.com/kcp-dev/contrib-filteredapiexport-vw/sdk/client/listers/filteredvw/v1alpha1"
)

// FilteredAPIExportEndpointSliceClusterInformer provides access to a shared informer and lister for
// FilteredAPIExportEndpointSlices.
type FilteredAPIExportEndpointSliceClusterInformer interface {
	Cluster(logicalcluster.Name) FilteredAPIExportEndpointSliceInformer
	Informer() kcpcache.ScopeableSharedIndexInformer
	Lister() filteredvwv1alpha1listers.FilteredAPIExportEndpointSliceClusterLister
}

type filteredAPIExportEndpointSliceClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewFilteredAPIExportEndpointSliceClusterInformer constructs a new informer for FilteredAPIExportEndpointSlice type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAPIExportEndpointSliceClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredFilteredAPIExportEndpointSliceClusterInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredFilteredAPIExportEndpointSliceClusterInformer constructs a new informer for FilteredAPIExportEndpointSlice type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredFilteredAPIExportEndpointSliceClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) kcpcache.ScopeableSharedIndexInformer {
	return kcpinformers.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FilteredvwV1alpha1().FilteredAPIExportEndpointSlices().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FilteredvwV1alpha1().FilteredAPIExportEndpointSlices().Watch(context.TODO(), options)
			},
		},
		&filteredvwv1alpha1.FilteredAPIExportEndpointSlice{},
		resyncPeriod,
		indexers,
	)
}

func (f *filteredAPIExportEndpointSliceClusterInformer) defaultInformer(client clientset.ClusterInterface, resyncPeriod time.Duration) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredFilteredAPIExportEndpointSliceClusterInformer(client, resyncPeriod, cache.Indexers{
		kcpcache.ClusterIndexName: kcpcache.ClusterIndexFunc,
	},
		f.tweakListOptions,
	)
}

func (f *filteredAPIExportEndpointSliceClusterInformer) Informer() kcpcache.ScopeableSharedIndexInformer {
	return f.factory.InformerFor(&filteredvwv1alpha1.FilteredAPIExportEndpointSlice{}, f.defaultInformer)
}

func (f *filteredAPIExportEndpointSliceClusterInformer) Lister() filteredvwv1alpha1listers.FilteredAPIExportEndpointSliceClusterLister {
	return filteredvwv1alpha1listers.NewFilteredAPIExportEndpointSliceClusterLister(f.Informer().GetIndexer())
}

// FilteredAPIExportEndpointSliceInformer provides access to a shared informer and lister for
// FilteredAPIExportEndpointSlices.
type FilteredAPIExportEndpointSliceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() filteredvwv1alpha1listers.FilteredAPIExportEndpointSliceLister
}

func (f *filteredAPIExportEndpointSliceClusterInformer) Cluster(clusterName logicalcluster.Name) FilteredAPIExportEndpointSliceInformer {
	return &filteredAPIExportEndpointSliceInformer{
		informer: f.Informer().Cluster(clusterName),
		lister:   f.Lister().Cluster(clusterName),
	}
}

type filteredAPIExportEndpointSliceInformer struct {
	informer cache.SharedIndexInformer
	lister   filteredvwv1alpha1listers.FilteredAPIExportEndpointSliceLister
}

func (f *filteredAPIExportEndpointSliceInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

func (f *filteredAPIExportEndpointSliceInformer) Lister() filteredvwv1alpha1listers.FilteredAPIExportEndpointSliceLister {
	return f.lister
}

type filteredAPIExportEndpointSliceScopedInformer struct {
	factory          internalinterfaces.SharedScopedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

func (f *filteredAPIExportEndpointSliceScopedInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&filteredvwv1alpha1.FilteredAPIExportEndpointSlice{}, f.defaultInformer)
}

func (f *filteredAPIExportEndpointSliceScopedInformer) Lister() filteredvwv1alpha1listers.FilteredAPIExportEndpointSliceLister {
	return filteredvwv1alpha1listers.NewFilteredAPIExportEndpointSliceLister(f.Informer().GetIndexer())
}

// NewFilteredAPIExportEndpointSliceInformer constructs a new informer for FilteredAPIExportEndpointSlice type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAPIExportEndpointSliceInformer(client scopedclientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredFilteredAPIExportEndpointSliceInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredFilteredAPIExportEndpointSliceInformer constructs a new informer for FilteredAPIExportEndpointSlice type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredFilteredAPIExportEndpointSliceInformer(client scopedclientset.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FilteredvwV1alpha1().FilteredAPIExportEndpointSlices().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FilteredvwV1alpha1().FilteredAPIExportEndpointSlices().Watch(context.TODO(), options)
			},
		},
		&filteredvwv1alpha1.FilteredAPIExportEndpointSlice{},
		resyncPeriod,
		indexers,
	)
}

func (f *filteredAPIExportEndpointSliceScopedInformer) defaultInformer(client scopedclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredFilteredAPIExportEndpointSliceInformer(client, resyncPeriod, cache.Indexers{}, f.tweakListOptions)
}
