/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	"github.com/kcp-dev/logicalcluster/v3"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"

	filteredvwv1alpha1 "github.com/kcp-dev/contrib-filteredapiexport-vw/sdk/apis/filteredvw/v1alpha1"
)

// FilteredAPIExportEndpointSliceClusterLister can list FilteredAPIExportEndpointSlices across all workspaces, or scope down to a FilteredAPIExportEndpointSliceLister for one workspace.
// All objects returned here must be treated as read-only.
type FilteredAPIExportEndpointSliceClusterLister interface {
	// List lists all FilteredAPIExportEndpointSlices in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*filteredvwv1alpha1.FilteredAPIExportEndpointSlice, err error)
	// Cluster returns a lister that can list and get FilteredAPIExportEndpointSlices in one workspace.
	Cluster(clusterName logicalcluster.Name) FilteredAPIExportEndpointSliceLister
	FilteredAPIExportEndpointSliceClusterListerExpansion
}

type filteredAPIExportEndpointSliceClusterLister struct {
	indexer cache.Indexer
}

// NewFilteredAPIExportEndpointSliceClusterLister returns a new FilteredAPIExportEndpointSliceClusterLister.
// We assume that the indexer:
// - is fed by a cross-workspace LIST+WATCH
// - uses kcpcache.MetaClusterNamespaceKeyFunc as the key function
// - has the kcpcache.ClusterIndex as an index
func NewFilteredAPIExportEndpointSliceClusterLister(indexer cache.Indexer) *filteredAPIExportEndpointSliceClusterLister {
	return &filteredAPIExportEndpointSliceClusterLister{indexer: indexer}
}

// List lists all FilteredAPIExportEndpointSlices in the indexer across all workspaces.
func (s *filteredAPIExportEndpointSliceClusterLister) List(selector labels.Selector) (ret []*filteredvwv1alpha1.FilteredAPIExportEndpointSlice, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*filteredvwv1alpha1.FilteredAPIExportEndpointSlice))
	})
	return ret, err
}

// Cluster scopes the lister to one workspace, allowing users to list and get FilteredAPIExportEndpointSlices.
func (s *filteredAPIExportEndpointSliceClusterLister) Cluster(clusterName logicalcluster.Name) FilteredAPIExportEndpointSliceLister {
	return &filteredAPIExportEndpointSliceLister{indexer: s.indexer, clusterName: clusterName}
}

// FilteredAPIExportEndpointSliceLister can list all FilteredAPIExportEndpointSlices, or get one in particular.
// All objects returned here must be treated as read-only.
type FilteredAPIExportEndpointSliceLister interface {
	// List lists all FilteredAPIExportEndpointSlices in the workspace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*filteredvwv1alpha1.FilteredAPIExportEndpointSlice, err error)
	// Get retrieves the FilteredAPIExportEndpointSlice from the indexer for a given workspace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*filteredvwv1alpha1.FilteredAPIExportEndpointSlice, error)
	FilteredAPIExportEndpointSliceListerExpansion
}

// filteredAPIExportEndpointSliceLister can list all FilteredAPIExportEndpointSlices inside a workspace.
type filteredAPIExportEndpointSliceLister struct {
	indexer     cache.Indexer
	clusterName logicalcluster.Name
}

// List lists all FilteredAPIExportEndpointSlices in the indexer for a workspace.
func (s *filteredAPIExportEndpointSliceLister) List(selector labels.Selector) (ret []*filteredvwv1alpha1.FilteredAPIExportEndpointSlice, err error) {
	err = kcpcache.ListAllByCluster(s.indexer, s.clusterName, selector, func(i interface{}) {
		ret = append(ret, i.(*filteredvwv1alpha1.FilteredAPIExportEndpointSlice))
	})
	return ret, err
}

// Get retrieves the FilteredAPIExportEndpointSlice from the indexer for a given workspace and name.
func (s *filteredAPIExportEndpointSliceLister) Get(name string) (*filteredvwv1alpha1.FilteredAPIExportEndpointSlice, error) {
	key := kcpcache.ToClusterAwareKey(s.clusterName.String(), "", name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(filteredvwv1alpha1.Resource("filteredapiexportendpointslices"), name)
	}
	return obj.(*filteredvwv1alpha1.FilteredAPIExportEndpointSlice), nil
}

// NewFilteredAPIExportEndpointSliceLister returns a new FilteredAPIExportEndpointSliceLister.
// We assume that the indexer:
// - is fed by a workspace-scoped LIST+WATCH
// - uses cache.MetaNamespaceKeyFunc as the key function
func NewFilteredAPIExportEndpointSliceLister(indexer cache.Indexer) *filteredAPIExportEndpointSliceScopedLister {
	return &filteredAPIExportEndpointSliceScopedLister{indexer: indexer}
}

// filteredAPIExportEndpointSliceScopedLister can list all FilteredAPIExportEndpointSlices inside a workspace.
type filteredAPIExportEndpointSliceScopedLister struct {
	indexer cache.Indexer
}

// List lists all FilteredAPIExportEndpointSlices in the indexer for a workspace.
func (s *filteredAPIExportEndpointSliceScopedLister) List(selector labels.Selector) (ret []*filteredvwv1alpha1.FilteredAPIExportEndpointSlice, err error) {
	err = cache.ListAll(s.indexer, selector, func(i interface{}) {
		ret = append(ret, i.(*filteredvwv1alpha1.FilteredAPIExportEndpointSlice))
	})
	return ret, err
}

// Get retrieves the FilteredAPIExportEndpointSlice from the indexer for a given workspace and name.
func (s *filteredAPIExportEndpointSliceScopedLister) Get(name string) (*filteredvwv1alpha1.FilteredAPIExportEndpointSlice, error) {
	key := name
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(filteredvwv1alpha1.Resource("filteredapiexportendpointslices"), name)
	}
	return obj.(*filteredvwv1alpha1.FilteredAPIExportEndpointSlice), nil
}
