//go:build !ignore_autogenerated

/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	conditionsv1alpha1 "github.com/kcp-dev/sdk/apis/third_party/conditions/apis/conditions/v1alpha1"

	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExportBindingReference) DeepCopyInto(out *ExportBindingReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExportBindingReference.
func (in *ExportBindingReference) DeepCopy() *ExportBindingReference {
	if in == nil {
		return nil
	}
	out := new(ExportBindingReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilteredAPIExportEndpointSlice) DeepCopyInto(out *FilteredAPIExportEndpointSlice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilteredAPIExportEndpointSlice.
func (in *FilteredAPIExportEndpointSlice) DeepCopy() *FilteredAPIExportEndpointSlice {
	if in == nil {
		return nil
	}
	out := new(FilteredAPIExportEndpointSlice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FilteredAPIExportEndpointSlice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilteredAPIExportEndpointSliceList) DeepCopyInto(out *FilteredAPIExportEndpointSliceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FilteredAPIExportEndpointSlice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilteredAPIExportEndpointSliceList.
func (in *FilteredAPIExportEndpointSliceList) DeepCopy() *FilteredAPIExportEndpointSliceList {
	if in == nil {
		return nil
	}
	out := new(FilteredAPIExportEndpointSliceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FilteredAPIExportEndpointSliceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilteredAPIExportEndpointSliceSpec) DeepCopyInto(out *FilteredAPIExportEndpointSliceSpec) {
	*out = *in
	out.APIExport = in.APIExport
	in.ObjectSelector.DeepCopyInto(&out.ObjectSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilteredAPIExportEndpointSliceSpec.
func (in *FilteredAPIExportEndpointSliceSpec) DeepCopy() *FilteredAPIExportEndpointSliceSpec {
	if in == nil {
		return nil
	}
	out := new(FilteredAPIExportEndpointSliceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilteredAPIExportEndpointSliceStatus) DeepCopyInto(out *FilteredAPIExportEndpointSliceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(conditionsv1alpha1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilteredAPIExportEndpointSliceStatus.
func (in *FilteredAPIExportEndpointSliceStatus) DeepCopy() *FilteredAPIExportEndpointSliceStatus {
	if in == nil {
		return nil
	}
	out := new(FilteredAPIExportEndpointSliceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilteredAPIExportObjectSelector) DeepCopyInto(out *FilteredAPIExportObjectSelector) {
	*out = *in
	in.LabelSelector.DeepCopyInto(&out.LabelSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilteredAPIExportObjectSelector.
func (in *FilteredAPIExportObjectSelector) DeepCopy() *FilteredAPIExportObjectSelector {
	if in == nil {
		return nil
	}
	out := new(FilteredAPIExportObjectSelector)
	in.DeepCopyInto(out)
	return out
}
